# Generated by Django 5.1.7 on 2026-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeopoliticalNews",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("source_name", models.CharField(max_length=100)),
                ("url", models.URLField(unique=True)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[("BD", "Bangladesh"), ("World", "World")],
                        default="World",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField()),
                ("bias_score", models.FloatField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
