# Generated by Django 5.1.7 on 2026-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geopoliticalnews",
            name="full_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
