# Generated by Django 5.1.7 on 2026-03-19 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_geopoliticalnews_full_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geopoliticalnews",
            options={
                "ordering": ["-published_at"],
                "verbose_name_plural": "Geopolitical News",
            },
        ),
        migrations.AddField(
            model_name="geopoliticalnews",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="geopoliticalnews",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="geopoliticalnews",
            name="source_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="geopoliticalnews",
            name="url",
            field=models.URLField(max_length=800, unique=True),
        ),
    ]
