# Generated by Django 5.1.7 on 2026-03-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_geopoliticalnews_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geopoliticalnews",
            name="full_text",
        ),
    ]
