# Generated by Django 5.1.7 on 2026-03-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_remove_geopoliticalnews_full_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="geopoliticalnews",
            name="objectivity_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
