# Generated by Django 5.1.7 on 2026-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_geopoliticalnews_objectivity_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geopoliticalnews",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
